### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by K1ltu** [Ordinastie/MalisisDoors#100]
when breaking doors 2 are dropped instead of one
nothing is printed to console

Mod ver 5.0.4
MC ver 1.10.2
Forge 2053

**Comment by miuirussia** [comment]
Confirm it!

**Comment by snurre0** [comment]
Me too! Happens to all kind of door from this mod, included vanilla doors, except maybe the garage door.
It also changes the item name when I break it. "Oak door" will be named "Oak door rotating", and will not stack with newly crafted doors.

**Comment by MysticAura** [comment]
This is an ongoing bug which I truly hope gets resolved soon.

MC Version: 1.10.2
Forge Version: 2086
Mod Version: 1.9.4-5.0.4

Bug #1
Steps to Reproduce: Break a door with your hand and you get two back instead of one. Duplicated door is altered to the rotating version.

Bug #2
Steps to Reproduce: Place a hatch in a 2x2 empty space. It tries to place but disappears instead (it's actually gone not just invisible). If you place in a 3x3 it places properly (but only takes 2x2 of space).

**Comment by Carrots4U** [comment]
Can confirm, occurs in All the Mods modpack.

**Comment by Ordinastie** [comment]
Fixed in 1.10.2-5.1.0
