### ISSUE TITLE
Conflict with Liteloader

### ISSUE THREAD

**Issue by Renadarain** [Ordinastie/MalisisDoors#170]
Hi,

MC: 1.12.1
Forge: 1.12.1-14.22.0.2456
Malisis Core: 1.12-6.0.4
Malisis Doors: 1.12-7.0.4
Liteloader:  1.12.1

Not sure if this is a Liteloader problem or Malisis Doors.  With just Forge, Malisis Doors and Liteloader loaded all vanilla doors change to the black/pink blocks.

Regards,
Renada

**Comment by JumpyDragon** [comment]
This is mostly just a "me too" post.... I don't know either if it's Malisis Doors or Liteloader (I'm kinda leaning towards Liteloader at the moment). Thanks for posting though, because after removing Liteloader, I can FINALLY let Malisis Doors modify the vanilla doors without the black-and-purple "missing texture" image that has plagued my heavily-modded worlds since... ever.

In case it helps, here's my game details after removing all other mods: (currently 1.12.1, but I have had this issue in many previous versions of MC/Forge/Liteloader as well)
MC 1.12.1
Liteloader 1.12.1
Forge 14.22.0.2469 (and many previous versions)
Malisis Core 1.12-6.0.4 (and previous)
Malisis Doors 1.12-7.0.4 (and previous)

(Not that it's really relevant to anyone else, but, sadly for me, I had to remove Light Level Overlay Reloaded and also switch from Voxelmap to JourneyMap. Probably because my PC is oooooooold, JourneyMap lags my game terribly during saving and also loading new chunks. But it is better than no mini-map at all! I have an even worse sense of direction in games than I do in real life..... BUT I LOVE ME SOME CUSTOM DOORS.)

**Comment by Ordinastie** [comment]
Will be fixed in the next update.
