### ISSUE TITLE
Bugs.

### ISSUE THREAD

**Issue by alexw235** [Ordinastie/MalisisDoors#185]
Found a few new bugs.

1)  When you try and make one of the malisis doors trapdoors via a crafting table, it gives back an original minecraft type trapdoor and not one from your mod.  The problem seems to arise from a clash in the crafting recipes.

2)  When you break a rusty ladder piece it gives back nothing instead of the ladder piece.

3)  If you dig a 1 block tunnel straight downwards, place in a trapdoor flush with the ground, and then put in the rusty ladder in that tunnel you can't actually climb out the tunnel.  The ladder doesn't give you enough height to climb out.  The in game ladder doesn't work like that.  So if you swap your rusty ladder with the in game ladder you can actually climb out.

**Comment by Ordinastie** [comment]
1. MalisisDoors trapdoors are not separate from Vanilla. Vanilla trapdoors should have the animation.

2. It's because you probably broke them with hand. They're made of iron, so they require a pickaxe to drop as item. However, I forgot to set a hardness, so you could break them instantly by hand too. That will be fixed in the next version.

3. It will be fixed in the next version.
