### ISSUE TITLE
Strange issue when opening door.

### ISSUE THREAD

**Issue by vico93** [Ordinastie/MalisisDoors#237]
Its hard to explain, so i made a [quick video](https://www.youtube.com/watch?v=ynEeJGzV4jw&feature=youtu.be).

Basically when i right-click to open a door a left-click action is also triggered, and the right-click action is "carried" for any blocks behind the door. So, if there a furnace, chest or other similar block behind the door it will be activated. Its mostly a small cosmetic issue, but it can be annoying if you (like me in the video) squeeze in a small hole in the beggining of the survival.

I just became aware of this after installing @OreCruncher 's [DynamicSurrondings](https://github.com/OreCruncher/DynamicSurroundings/), because it adds (loud) sounds for these actions (the sword slashing is normally fired only when we left-click a sword pointing to sky).

Also, there's no error or issue on logs. What it could be?

**Comment by Ordinastie** [comment]
Does it happen when you only have MalisisDoors installed ?
You should also check if that happen without MalisisDoors even.

**Comment by OreCruncher** [comment]
The furnace one isn't me. :)  However, the sound playing at the end of the video when opening the door is Dynamic Surroundings.  Currently trying to sort that one out as it relates to ray tracing and block hits.  You will get the swing sound because the ray trace did not hit any blocks.

**Comment by vico93** [comment]
@Ordinastie i will setup a temp profile only with malisis mods installed, hang a sec

**Comment by vico93** [comment]
Tested only using MalisisDoors, not see the issue happening. Then i installed DynamicSurrondings: the left-click sound when opening door happens. Plus, if i right-click too fast or when the door animation is playing the container behind will open.
If @OreCruncher want i could recreate the issue in his repo.

**Comment by Ordinastie** [comment]
Ok, that's two different things.
When a door is opening, during the animation, it doesn't have any hitbox. So if you right click again, it will trigger on whatever is behind it.
As for the sword sound, if I understand correctly, you're saying that when you right click **once**, you hear the same sound as if you left clicked ? If that's the case, I would assume it's an issue for DynamicSurroundigs.

**Comment by OreCruncher** [comment]
The swing logic in DS is triggered because it detects an entity, in this case the player, swinging it's arms.  It doesn't know if it is a right or left click - just that the arms are swinging.  When that happens DS performs a raytrace to see what the player is swinging at.  On a door open the door is open *before* the DS logic kicks in thus the raytrace goes through the door to whatever is behind.  If the trace doesn't hit anything you get the swing sound (like what is seen in the video).  If there was something behind the door (like a block) and that block is within the swing distance of the player, no sound would play because the raytrace would have reported a block hit.  If the player were to close the door no sound would play because the raytrace would hit the closed door.

The upshot to all this is that the sword swing sound is not a Malisis issue but something in DS.

**Comment by vico93** [comment]
Created the ticket on DS repository.
