### ISSUE TITLE
Mod compatibility issue with Archimedes Ships

### ISSUE THREAD

**Issue by DLemberg** [Ordinastie/MalisisDoors#31]
I created an airship with Archimedes Ships in a 1.7.10 multiplayer world, and added a Malisis Doors' rusty hatch to the airship.  The ship assembled and moved fine.  But when I disassembled the ship back into blocks, the rusty hatch became invisible and unbreakable.  I knew it was still there because I couldn't place blocks where it used to be in a 2x2 block area, 3 blocks high.  In addition, water would flow around it, etc. as if it was still there, but it couldn't be opened, closed, seen, or (especially) removed.  It is as if the rusty hatch was there to the server, but not to the client.  Only way to fix the world was to remove Malisis Doors, load & then close the world, and readd Malisis Doors.

**Comment by voidswrath** [comment]
That isn't an issue with Malisis Doors its how archimedes handles assembling the ship and dissembling. Try using decocraft and then it would all revert to the creeper plushie. Well that would be decocrafts issue because similar to archimedes world edit will make it all turn to stuffed creepers. It just doesn't handle blocks like normal minecraft which is what archimedes is counting on.
