### ISSUE TITLE
[1.8.9] MalisisCore & MalisisDoors - memory leak.

### ISSUE THREAD

**Issue by MrGraphic** [Ordinastie/MalisisDoors#81]
Forge .1764
MalisisCore 2.1.1
MalisisDoor 3.1.1

Took me a while to isolate issue from the whole pack. Apparently there is a "hole" somewhere. Byte and Char arrays growing way beyond normal state. 
Totally fresh save, no blocks of interest in world, standing still, vanilla plus core and doors.
Fancy picture from profiling:
![m_core_door](https://cloud.githubusercontent.com/assets/4780141/13892205/b087e484-ed4d-11e5-85f5-2bb8d835649e.jpg)
and for comparison vanilla plus thaumcraft:
![m_core_door_tc_c](https://cloud.githubusercontent.com/assets/4780141/13892274/2fab4d8c-ed4e-11e5-8223-ed0c759891ad.jpg)

**Comment by Ordinastie** [comment]
I had multiple report of memory leaks from MalisisDoors, but I haven't been able to find out from where it comes. I'll keep looking though...

**Comment by MrGraphic** [comment]
Unfortunelly I can't provide more details. 
Heap is filling even if only MalisisCore is in enviroment.

**Comment by Ordinastie** [comment]
Ok, I may have found a leak, but it doesn't really makes sense for your test case.
First, that's what I have : http://puu.sh/nM9Lo.png. As you can see, memory doesn't really ramp up, and that's in dev, with all my mods together.
Anyhow, I found some objects piling up in memory, but that happens when new chunks get loaded on the server, which doesn't really apply in your test case.

However, if you manage to find the time to redo your test, but when done, perform a Head Dump.
For that dump, on the Classes tab, if you can filter with the word "malisis" and screen that, I could confirm that I did find the leak.

**Comment by MrGraphic** [comment]
Ok, first of all from what I have seen so far dev env is somekind of a "magic place" where even if you cut half the code things will still work as expected hehe ;). 
Second, it seems that the last commit did the trick and perm gen does not swell anymore :D. Fantastic job!
Screen from heap dump as instrumented :
![classes](https://cloud.githubusercontent.com/assets/4780141/13901580/946ecd5c-ee20-11e5-8b1f-d8aa1bf76d41.jpg)

**Comment by Ordinastie** [comment]
I was hoping for the buggy screen, but if you say it's fixed, I'll trust you :)

**Comment by MrGraphic** [comment]
Hehe, we will see in "real life" case ;).
